name: npcmc-core
version: '${project.version}'
main: dev.flur.npcmccore.npcmcCore
api-version: '1.20'
authors: ["flurbudurbur"]

dependencies:
  server:
    PlaceholderAPI:
      # Load order is relative to the dependency. So here PlaceholderAPI loads before our plugin.
      load: BEFORE
      required: true
